apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: edupplan
type: Opaque
stringData:
  POSTGRES_USER: eduplan_user
  POSTGRES_PASSWORD: eduplan_password
  POSTGRES_DB: eduplan_db
